---
name: Test
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # This fetches all branches and tags, which helps us lint that we're using the current version
        # in our examples.
        fetch-depth: 0
    - run:
        make lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run:
        make test
